name: build

on:
#  release:
#    types: [published]
  push:
    branches:
      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5

    
env:
  ROM_URL: https://218-60-174-249.d.cjjd15.com:30443/download-cdn.123pan.cn/123-104/af52cff0/1812435082-0/af52cff0f4b1b6c3a57990b2ce786468/c-m5?v=5&t=1687425204&s=1687425204ef88b76f0df53d3695b66a6259e8e562&r=YHU05Q&filename=Raphael_OriginOS3.0_PD2141_8.14.0_release5.1.5.7z&x-mf-biz-cid=743d83aa-7fcf-489b-a97d-b52dc667d877-584000&auto_redirect=0&xmfcid=6076f8b5-8d0f-46b7-85cb-304c396f8e7e-0-50111d3b1
  ROM_NAME: Generic
  BUILD_TYPE: ab
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initialization environment
         run: |
              sudo apt install git
              echo "BUILD_TIME=$(date +%s | md5sum | awk '{print substr($1,1,10)}')" >> $GITHUB_ENV
           
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/mi20210630/ErfanGSIs.git ErfanGSIs
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
       
       - name: Setting up ErfanGSI requirements
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs
              mkdir ./output
              sudo bash ./setup.sh
              java -version
              pip3 install aligo
              
       - name: Download Stock Rom & Generate GSI
         run: |
             cd $GITHUB_WORKSPACE/ErfanGSIs
             sudo bash ./url2GSI.sh -c --$BUILD_TYPE $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              zip -r GSI.zip ./*
              mkdir upload
              if [[ $(du -sb "GSI.zip" | awk '{print $1}') -gt 2097152000 ]];then
                  echo -e "split packaging..."
                  tar -cpzf - "GSI.zip" | split -d -b 1024m - "upload/GSI.zip"
              else 
                  mv GSI.zip upload/
              fi
              ls "upload"                  
              
       - name: Upload GSI to release
         uses: ncipollo/release-action@v1.8.6
         with:
           artifacts: ${{ github.workspace }}/ErfanGSIs/output/upload/*
           tag: ErfanGSIs-${{ env.ROM_NAME }}-${{ env.BUILD_TYPE }}-${{ env.BUILD_TIME }}
           bodyFile: "${{ github.workspace }}/ErfanGSIs/output/info.txt"
           token: ${{ secrets.PAT }}
